#pragma once

#include <stdint.h>

/* Available protocol versions */

static const uint8_t PROTOCOL_VERSION_28 = 28;
static const uint8_t PROTOCOL_VERSION_140 = 140;

/* Server packets */

struct ServerPacketProtocol {
	uint8_t DIE;
	uint8_t	REVIVE;
	uint8_t	DELETE_OBJECT;
	uint8_t CHAR_SELECTED;
	uint8_t EX_NPC_INFO;
	uint8_t ITEM_LIST;
	uint8_t DROP_ITEM;
	uint8_t GET_ITEM;
	uint8_t STATUS_UPDATE;
	uint8_t ACTION_FAIL;
	uint8_t TARGET_SELECTED;
	uint8_t TARGET_UNSELECTED;
	uint8_t AUTO_ATTACK_START;
	uint8_t SOCIAL_ACTION;
	uint8_t CHANGE_WAIT_TYPE;
	uint8_t MOVE_TO_LOCATION;
	uint8_t CHARINFO;
	uint8_t EX_USER_INFO;
	uint8_t ATTACK;
	uint8_t STOP_MOVE;
	uint8_t MAGIC_SKILL_USE;
	uint8_t MAGIC_SKILL_CANCELED;
	uint8_t EX_NPC_INFO_ABNORMAL_VISUAL_EFFECT;
	uint8_t MAGIC_SKILL_LAUNCHED;
	uint8_t SKILL_LIST;
	uint8_t SYSTEM_MESSAGE;
	uint8_t RESTART_RESPONSE;
	uint8_t MOVE_TO_PAWN;
	uint8_t S_VALIDATE_LOCATION;
	uint8_t DUMMY_7D;
	uint8_t QUEST_LIST;
	uint8_t EX_ACQUIRABLE_SKILL_LIST_BY_CLASS;
	uint8_t MY_TARGET_SELECTED;
	uint8_t NET_PING;
	uint8_t MACRO_LIST;
	uint8_t SPKT_FE;
};

struct ServerPacketProtocolSpecial {
	uint8_t EX_EVENT_MATCH_TEAM_UNLOCKED;
	uint8_t EX_EVENT_MATCH_CREATE;
	uint8_t EX_SEND_MANOR_LIST;
	uint8_t PLEDGE_RECEIVE_POWER_INFO;
	uint8_t EX_GET_BOOKMARK_INFO;
	uint8_t EX_QUEST_ITEM_LIST;
	uint8_t EXBR_AGATHION_ENERGY_INFO;
	uint8_t EX_SUBJOBINFO;
};

/* Client packets */

struct ClientPacketProtocol {
	uint8_t MOVE_BACKWARD_TO_LOCATION;
	uint8_t ACTION;
	uint8_t REQUEST_MAGIC_SKILL_USE;
	uint8_t REQUEST_ACTION_USE;
	uint8_t VALIDATE_LOCATION;
};

/* Implementations */

// Protocol version 28 (L2Classic 1.5?)

static const ServerPacketProtocol ServerPacketP28 = {
	0x00, // DIE
	0x01, // REVIVE
	0x08, // DELETE_OBJECT
	0x0B, // CHAR_SELECTED
	0x0C, // EX_NPC_INFO
	0x11, // ITEM_LIST
	0x16, // DROP_ITEM
	0x17, // GET_ITEM
	0x18, // STATUS_UPDATE
	0x1F, // ACTION_FAIL
	0x23, // TARGET_SELECTED
	0x24, // TARGET_UNSELECTED
	0x25, // AUTO_ATTACK_START
	0x27, // SOCIAL_ACTION
	0x29, // CHANGE_WAIT_TYPE
	0x2F, // MOVE_TO_LOCATION
	0x31, // CHARINFO
	0x32, // EX_USER_INFO
	0x33, // ATTACK
	0x47, // STOP_MOVE
	0x48, // MAGIC_SKILL_USE
	0x49, // MAGIC_SKILL_CANCELED
	0x4B, // EX_NPC_INFO_ABNORMAL_VISUAL_EFFECT
	0x54, // MAGIC_SKILL_LAUNCHED
	0x5F, // SKILL_LIST
	0x62, // SYSTEM_MESSAGE
	0x71, // RESTART_RESPONSE
	0x72, // MOVE_TO_PAWN
	0x79, // S_VALIDATE_LOCATION
	0x7D, // DUMMY_7D
	0x86, // QUEST_LIST
	0x90, // EX_ACQUIRABLE_SKILL_LIST_BY_CLASS
	0xB9, // MY_TARGET_SELECTED
	0xD9, // NET_PING
	0xE8, // MACRO_LIST
	0xFE, // SPKT_FE
};

static const ServerPacketProtocolSpecial ServerPacketSpecialP28 = {
	0x06, // EX_EVENT_MATCH_TEAM_UNLOCKED
	0x1D, // EX_EVENT_MATCH_CREATE
	0x22, // EX_SEND_MANOR_LIST
	0x3E, // PLEDGE_RECEIVE_POWER_INFO
	0x85, // EX_GET_BOOKMARK_INFO
	0xC7, // EX_QUEST_ITEM_LIST
	0xDF, // EXBR_AGATHION_ENERGY_INFO
	0xEA, // EX_SUBJOBINFO
};

static const ClientPacketProtocol ClientPacketP28 = {
	0x0F, // MOVE_BACKWARD_TO_LOCATION
	0x1F, // ACTION
	0x39, // REQUEST_MAGIC_SKILL_USE
	0x56, // REQUEST_ACTION_USE
	0x59, // VALIDATE_LOCATION
};

// Protocol version 140 (L2Classic 3.0?)

static const ServerPacketProtocol ServerPacketP140 = {
	0x00, // DIE
	0x01, // REVIVE
	0x08, // DELETE_OBJECT
	0x0B, // CHAR_SELECTED
	0x0C, // EX_NPC_INFO
	0x11, // ITEM_LIST
	0x16, // DROP_ITEM
	0x17, // GET_ITEM
	0x18, // STATUS_UPDATE
	0x1F, // ACTION_FAIL
	0x23, // TARGET_SELECTED
	0x24, // TARGET_UNSELECTED
	0x25, // AUTO_ATTACK_START
	0x27, // SOCIAL_ACTION
	0x29, // CHANGE_WAIT_TYPE
	0x2F, // MOVE_TO_LOCATION
	0x31, // CHARINFO
	0x32, // EX_USER_INFO
	0x33, // ATTACK
	0x47, // STOP_MOVE
	0x48, // MAGIC_SKILL_USE
	0x49, // MAGIC_SKILL_CANCELED
	0x4B, // EX_NPC_INFO_ABNORMAL_VISUAL_EFFECT
	0x54, // MAGIC_SKILL_LAUNCHED
	0x5F, // SKILL_LIST
	0x62, // SYSTEM_MESSAGE
	0x71, // RESTART_RESPONSE
	0x72, // MOVE_TO_PAWN
	0x79, // S_VALIDATE_LOCATION
	0x7D, // DUMMY_7D
	0x86, // QUEST_LIST
	0x90, // EX_ACQUIRABLE_SKILL_LIST_BY_CLASS
	0xB9, // MY_TARGET_SELECTED
	0xD9, // NET_PING
	0xE8, // MACRO_LIST
	0xFE, // SPKT_FE
};

static const ServerPacketProtocolSpecial ServerPacketSpecialP140 = {
	0x06, // EX_EVENT_MATCH_TEAM_UNLOCKED
	0x1D, // EX_EVENT_MATCH_CREATE
	0x22, // EX_SEND_MANOR_LIST
	0x3E, // PLEDGE_RECEIVE_POWER_INFO
	0x85, // EX_GET_BOOKMARK_INFO
	0xC7, // EX_QUEST_ITEM_LIST
	0xDF, // EXBR_AGATHION_ENERGY_INFO
	0xEA, // EX_SUBJOBINFO
};

static const ClientPacketProtocol ClientPacketP140 = {
	0x0F, // MOVE_BACKWARD_TO_LOCATION
	0x1F, // ACTION
	0x39, // REQUEST_MAGIC_SKILL_USE
	0x56, // REQUEST_ACTION_USE
	0x59, // VALIDATE_LOCATION
};